FROM python:3.8

WORKDIR /app

RUN apt-get update && apt-get install -y wget unzip
RUN pip install jinja2
RUN pip install gradio 

RUN wget -O MLP-20M.zip "https://www.dropbox.com/scl/fi/7ot2a906wmmovvi2jnbuq/MLP-20M.zip?rlkey=87r6wmfitc2r3s3uknyfy9cob&dl=1"
RUN unzip MLP-20M.zip -d /app
RUN rm MLP-20M.zip

# Créez le répertoire pour les dataframes
RUN mkdir -p /app/Model
RUN wget --no-check-certificate 'https://www.dropbox.com/scl/fi/tovknolbnnryjlqmaw7i7/new_vectoriseur.pkl?rlkey=k84j5durnxk9vktdwm2lu5ttg&dl=1' -O /app/Model/new_vectoriseur.pkl

COPY . /app

RUN pip install -r requirements.txt
RUN pip install scikit-learn

EXPOSE 7860

CMD ["python", "gradio_app.py"]