FROM python:3.8

WORKDIR /app

COPY . /app

RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN pip install annoy

EXPOSE 5066

ENV FLASK_ENV=production

CMD ["python","systeme_reco_api.py"]